### PR TITLE
Update requirement guidance

### PR DESCRIPTION
**Pull request by yolile**
Ref https://github.com/open-contracting/ocds-extensions/issues/123

### CODE REVIEW

**Comment by jpmckinney** [comment]
The requirements extension presently has nothing to do with metrics. https://extensions.open-contracting.org/en/extensions/requirements/master/schema/

We can resolve the issue either by deleting this entire section from the readme, or by adding the relevant field to the extension.

**Comment by yolile** [comment]
> We can resolve the issue either by deleting this entire section from the readme, or by adding the relevant field to the extension.

I will add the  'requirementResponses' array to the Metric definition in the requirements extension to satisfy the use case indicated in the readme:
>  "This can allow a degree of comparison between performance anticipated at bid, award, contract and implementation phases."

**Comment by yolile** [comment]
Or.. maybe is better to just remove the section from the readme? do we have a real user that use that? if no maybe we can remove the block for now and open a new issue into the requirements extension if someone wants to publish that information

**Comment by jpmckinney** [comment]
Let's remove it and not create the issue. The CCCEV model on which the requirements extension is based is already designed to express to what level a bid meets a requirement, so mixing in metrics is duplicative.

**Comment by yolile** [comment]
done

**Pull request merged**
